[versions]
alexrdclement-gradle-plugins = "0.0.70"
androidx-activity-compose = "1.12.2"
androidx-core-splashscreen = "1.2.0"
androidx-lifecycle = "2.10.0"
androidx-navigationevent = "1.0.1"
androidx-test-ext-junit = "1.3.0"
baselineprofile = "1.4.1"
benchmark-macro-junit4 = "1.4.1"
coil = "3.3.0"
compose-multiplatform-material3 = "1.10.0-alpha05"
compose-multiplatform-material-icons-extended = "1.7.3"
espresso-core = "3.7.0"
junit = "4.13.2"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-serialization-json = "1.9.0"
ktor = "3.3.3"
navigation-compose = "2.9.1"
navigation3-ui = "1.0.0-alpha06"
navigation3-browser = "0.3.1"
paparazzi = "2.0.0-alpha02"
profileinstaller = "1.4.1"
test-parameter-injector = "1.20"
tracing-perfetto = "1.0.1"
uiautomator = "2.3.0"
trace = "0.0.5"
uievent = "0.0.7"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigationevent = { group = "androidx.navigationevent", name = "navigationevent-compose", version.ref = "androidx-navigationevent" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-tracing-perfetto = { group = "androidx.tracing", name = "tracing-perfetto", version.ref = "tracing-perfetto" }
androidx-tracing-perfetto-binary = { group = "androidx.tracing", name = "tracing-perfetto-binary", version.ref = "tracing-perfetto" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-multiplatform-material3" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-multiplatform-material-icons-extended" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3-ui" }
navigation3-browser = { module = "com.github.terrakok:navigation3-browser", version.ref = "navigation3-browser" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }
test-parameter-injector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "test-parameter-injector" }
trace = { group = "com.alexrdclement.trace", name = "trace", version.ref = "trace" }
uievent = { group = "com.alexrdclement.uievent", name = "uievent", version.ref = "uievent" }

[plugins]
alexrdclement-android-application = { id = "com.alexrdclement.gradle.plugin.android.application", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-application-compose = { id = "com.alexrdclement.gradle.plugin.android.application.compose", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-baselineprofile-consumer = { id = "com.alexrdclement.gradle.plugin.android.baselineprofile.consumer", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-baselineprofile-generator = { id = "com.alexrdclement.gradle.plugin.android.baselineprofile.generator", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-benchmark = { id = "com.alexrdclement.gradle.plugin.android.benchmark", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-compose-test = { id = "com.alexrdclement.gradle.plugin.android.compose.test", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-library = { id = "com.alexrdclement.gradle.plugin.android.library", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-library-compose = { id = "com.alexrdclement.gradle.plugin.android.library.compose", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-android-test = { id = "com.alexrdclement.gradle.plugin.android.test", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-compose-multiplatform = { id = "com.alexrdclement.gradle.plugin.compose.multiplatform", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-desktop-application = { id = "com.alexrdclement.gradle.plugin.desktop.application", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-github-release = { id = "com.alexrdclement.gradle.plugin.github.release", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-kotlin-multiplatform-library = { id = "com.alexrdclement.gradle.plugin.kotlin.multiplatform.library", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-kotlin-serialization = { id = "com.alexrdclement.gradle.plugin.kotlin.serialization", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-maven-publish = { id = "com.alexrdclement.gradle.plugin.maven.publish", version.ref = "alexrdclement-gradle-plugins" }
alexrdclement-web-application = { id = "com.alexrdclement.gradle.plugin.web.application", version.ref = "alexrdclement-gradle-plugins" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

[bundles]
